[package]
name = "cloudflare-h3-observer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
common = { path = "../common" }
h3 = "0.0.8"
h3-quinn = "0.0.10"
http = "1"
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
webpki-roots = "1"

[dev-dependencies]
bytes = "1"
rcgen = "0.13"
rand.workspace = true
